[server]
port = 9096
debug = true

[auth]
username = "asdf"
password = "qwerty"

[db]
hostname = ""
port = ""
username = ""
password = ""
dbname = ""

[discord]
bot = ""

[reCAPTCHA]
secretKey = ""

[mailgun]
domain = "example.com"
receiver = "foo@example.com"
sender = "Foo <me@example.com>"
apiKey = "asdf"