[server]
port = 9096
debug = true

[auth]
username = "asdf"
password = "qwerty"

[db]
hostname = ""
port = ""
username = ""
password = ""
dbname = ""

[discord]
bot = "NTk2NjUxNjQ3NzI4NjE1NDI1.XR8pJg.IVeq8a8Z9_3DMPrjGhKTi74NxRU"